# Generated by Django 5.0.6 on 2024-06-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriz',
            name='autor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
